from articles.models import Article, Tags, ArticleTags
article1 = Article.objects.get(id=1)
article2 = Article.objects.get(id=2)
article3 = Article.objects.get(id=3)
teg1 = Tags.objects.create(name='Культура')
teg2 = Tags.objects.create(name='Город')
teg3 = Tags.objects.create(name='Покупки')
teg4 = Tags.objects.create(name='Здоровье')
teg5 = Tags.objects.create(name='Наука')
teg6 = Tags.objects.create(name='Космос')
teg7 = Tags.objects.create(name='Международные отношения')
teg8 = Tags.objects.create(name='проверка')

article1.tags.add(teg8)
article1.tags.add(teg3)
article2.tags.add(teg5)
article2.tags.add(teg8)
article3.tags.add(teg7)
article3.tags.add(teg8)
article3.tags.add(teg5)

teg4 = Tags.objects.get(id=4)
teg1 = Tags.objects.get(id=1)
teg6 = Tags.objects.get(id=6)
article1.tags.add(teg1)
article2.tags.add(teg4)
article3.tags.add(teg6)