# Generated by Django 2.2.1 on 2020-01-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200124_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-is_main', 'name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='tags',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
